# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
            git lfs pull
      - run:
          name: install python publisher and dependencies
          command: |
            git clone https://github.com/ShirtsToGit/wordpress-py publisher
            cd publisher
            virtualenv env
            source env/bin/activate
            pip install --quiet -r requirements.txt
            cd ..

      # run tests!
      - run:
          name: Publish to Test
          command: |
            ls -la
            pwd
            source publisher/env/bin/activate
            python publisher/main.py test

      - deploy:
          name: Publish to Prod (master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              source publisher/env/bin/activate
              python publisher/main.py prod
            fi
  
  